### ISSUE TITLE
I met two problems

### ISSUE THREAD

**Issue by NKU100** [adamhlt/D3D9-Hook-ImGui#2]
1. cannot free the Dll properly due to wrong use of FreeLibraryAndExitThread
2. tow mouse in game due to writing to io.WantCaptureMouse
ref: [You should never write to this value yourself](https://github.com/ocornut/imgui/issues/4593#issuecomment-930281293)

**Comment by adamhlt** [comment]
Hi, the unload problem has been resolved, I will work on the second point later.

**Comment by UncommonRuler** [comment]
I resolved them just now, there will be a PR soon.

**Comment by adamhlt** [comment]
I fixed all the problems in the last commit, now the DLL can be unloaded by an external signal and itself, and there is no more WantToCapture override. So I'm closing the issue.
