### ISSUE TITLE
game crashes and closes when changing resolution

### ISSUE THREAD

**Issue by jorgedev17** [adamhlt/D3D9-Hook-ImGui#7]
Hello friend, I used your source code in the game "WolfTeam" but when you change the resolution or when the game refreshes the screen everything freezes and sometimes closes, also in full screen when injected the game immediately closes

**Comment by adamhlt** [comment]
Thanks for reporting the issue, I will try to test it when I have free time.

**Comment by adamhlt** [comment]
@jorgedev17 Issue is fixed now with new commits
